Add code (uv replacement for vex)

diff --git a/bin/jo b/bin/jo
--- a/bin/jo
+++ b/bin/jo
@@ -32,7 +32,7 @@ if [[ "$target" == "help" ]]; then
   echo "  jo ud<foo> generic 3 way <foo>"
   echo "  jo cna"
   echo "  jo knog"
-  echo -e "  jo <proj>  4 way vbox of python project, <proj>\nProjects:"
+  echo -e "  jo <proj>  3 way uv run bash, $CODE/<proj>\nProjects:"
   ls $CODE
 elif [[ "${target:0:2}" == "ud" ]]; then
   ## 3way generic. Each ud must be unique.
@@ -47,39 +47,35 @@ elif [[ "$target" == "cna" ]]; then
   tmux -u split-window -t "$session:$target".3 -h
   tmux -u send-keys -t "$session:$target".1 "cd ~/Dropbox/code/cna/api;uv run ./manage.py runserver 127.0.0.1:8100" C-m
   tmux -u send-keys -t "$session:$target".2 "cd ~/Dropbox/code/cna/web;uv run python -m http.server 8000" C-m
-  tmux -u send-keys -t "$session:$target".3 "cd ~/Dropbox/code/cna/core;clear;ls" C-m
-  tmux -u send-keys -t "$session:$target".3 "uv run bash" C-m
-  tmux -u send-keys -t "$session:$target".4 "cd ~/Dropbox/code/cna/api;clear;ls" C-m
-  tmux -u send-keys -t "$session:$target".4 "uv run bash" C-m
+  tmux -u send-keys -t "$session:$target".3 "cd ~/Dropbox/code/cna/core;uv run bash" C-m
+  tmux -u send-keys -t "$session:$target".3 "ls" C-m
+  tmux -u send-keys -t "$session:$target".4 "cd ~/Dropbox/code/cna/api;uv run bash" C-m
+  tmux -u send-keys -t "$session:$target".4 "ls" C-m
   tmux -u select-pane -t "$session:$target".1
 elif [[ "$target" == "knog" ]]; then
-  ## 3-way SSH to target.
+  ## 3-way SSH to target
   # work pane left
   tmux -u new-window -n "$target" "ssh $target"
   # wide log below
   tmux -u split-window -t "$session:$target".1 -dv -l 20 "ssh $target"
-  sleep .5
-  tmux -u send-keys -t "$session:$target".2 'who' C-m
-  tmux -u send-keys -t "$session:$target".2 'uptime' C-m
-  # tmux -u send-keys -t "$session:$target".2 'clear;cd /var/log;echo "tailing some logs";sudo tail --follow=name messages syslog kern.log' C-m
   # root shell right
   tmux -u split-window -t "$session:$target".1 -dh -p 50 "ssh $target"
-  sleep .5
   tmux -u send-keys -t "$session:$target".2 'sudo bash' C-m
+  tmux -u send-keys -t "$session:$target".2 'uptime' C-m
+  tmux -u send-keys -t "$session:$target".3 'who' C-m
+  # tmux -u send-keys -t "$session:$target".2 'clear;cd /var/log;echo "tailing some logs";sudo tail --follow=name messages syslog kern.log' C-m
 else
-  # 4way dev
-  tmux -u new-window -n "$target"
-  tmux -u split-window -t "$session:$target".1 -v -l 40
-  tmux -u split-window -t "$session:$target".1 -h
-  tmux -u split-window -t "$session:$target".3 -h
-  tmux -u send-keys -t "$session:$target".1 "cd $CODE/$target" C-m
-  tmux -u send-keys -t "$session:$target".1 "uv run bash" C-m
-  tmux -u send-keys -t "$session:$target".2 "cd $CODE/$target" C-m
-  tmux -u send-keys -t "$session:$target".2 "uv run bash" C-m
-  tmux -u send-keys -t "$session:$target".3 "cd $CODE/$target" C-m
-  tmux -u send-keys -t "$session:$target".3 "uv run bash" C-m
-  tmux -u send-keys -t "$session:$target".3 "nukepyc;clear;tree" C-m
-  tmux -u send-keys -t "$session:$target".4 "cd $CODE/$target" C-m
-  tmux -u send-keys -t "$session:$target".4 "uv run bash" C-m
+  # 3-way dev
+  if [ ! -d "$CODE/$target" ]; then
+      echo "error: '$CODE/$target' not found" >&2
+      ls $CODE
+      exit 1
+  fi
+  tmux -u new-window -n "$target" -e "UV_PREVIEW=$UV_PREVIEW" -e "UV_PREVIEW_FEATURES=$UV_PREVIEW_FEATURES" "code $target"
+  tmux -u split-window -t "$session:$target".1 -v -l 40 -e "UV_PREVIEW=$UV_PREVIEW" -e "UV_PREVIEW_FEATURES=$UV_PREVIEW_FEATURES" "code $target"
+  tmux -u split-window -t "$session:$target".1 -h -e "UV_PREVIEW=$UV_PREVIEW" -e "UV_PREVIEW_FEATURES=$UV_PREVIEW_FEATURES" "code $target"
+  sleep .5
+  tmux -u send-keys -t "$session:$target".2 "nukepyc;tree" C-m
+  tmux -u send-keys -t "$session:$target".3 "ls" C-m
   tmux -u select-pane -t "$session:$target".1
 fi
